---
- name: install docker dependencies
  become: yes
  apt:
    name: apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common
    state: present

- name: add docker's GPG key
  become: yes
  shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

- name: verify fingerprint
  become: yes
  shell: apt-key fingerprint 0EBFCD88

- name: add docker repository
  become: yes
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: update cache
  become: yes
  apt:
    update_cache: yes

- name: upgrade system
  become: yes
  apt:
    upgrade: yes

- name: install docker engine
  become: yes
  apt:
    name: docker-ce, docker-ce-cli, containerd.io
    state: present
